config:
  base_path: D:\\cdz

logback:
  logdir: ${config.base_path}\\logs\\cdz-api
  appname: cdz-api
  ##打印输出等级
  level: info

#文件请求路径
url:
  base: http:\\192.168.2.18:8081
  #banner
  banner: ${url.base}\banner
  #t头像路径
  user_avatar: ${url.base}\user_avatar
  #站点路径
  station: ${url.base}\station

atomikos:
  logdir: ${config.base_path}\\logs\\cdz-api\\transaction-logs
  logname: cdz-api-transaction

jdbc:
  center:
      url: 192.168.2.123
      username: root
      password: 123456
  charging:
      url: 192.168.2.123
      username: root
      password: 123456

redis:
  url: 192.168.2.123
  password:

#激光推送
jpush:
  app_key: d67c63d217d62dc1c16a6a7c
  master_secret: f16eb1d9e0080ff33e1ff71b