server:
  port: 8010

spring:
  profiles:
    active: dev
  #atomic配置
  jta:
    atomikos:
      properties:
          log-base-dir: ${atomikos.logdir}
          log-base-name: ${atomikos.logname}
  redis:
        prot: 6379
        host: ${redis.url}
        password: ${redis.password}
        database: 1
        lettuce:
            pool:
               max-active: 8
               max-wait: -1ms
               max-idle: 500
               min-idle: 0
  servlet:
      multipart:
        max-request-size: 20Mb
        max-file-size: 20Mb

#多数据源配置
mysql:
  datasource:
    center:
      url: jdbc:mysql://${jdbc.center.url}:3306/DB_CENTER?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      username: ${jdbc.center.username}
      password: ${jdbc.center.password}
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1
    charging:
      url: jdbc:mysql://${jdbc.charging.url}:3306/DB_CHARGING?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      username: ${jdbc.charging.username}
      password: ${jdbc.charging.password}
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1


sms:
    id: LTAIWsKjeek9LEWo
    secret: l7QBI83XV18P6GFnrGFfTGSxpvPT8R
    signName: 贵安行
    templateCode: SMS_142946785
    #短信有效时间 5分钟=300秒
    timeout: 300


#参数加密私钥
privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAKvlz32eKywjFnlzhYRGS/W9nCB6r2FzRi3SaPfPh9Ln00kgGXT3ojY6QuG4SHMYsOVYc0k0wi877ASpQhy+wq7RGSlp0nPcg+kQN3QQvLU4ztFo45I2aDEO+iD2FR92wiYLYloRGwhU0mq8FEn+JbrWsmgyCiYExCK9txYjAo/XAgMBAAECgYBbIWJ2/jt1EsT/bjcCgSIUDYmPznrb9vjlof70IZmoPi7NPa9BS2c7yHdcow4FtrlRXSsBTG8GC4Z8kh7yjk827lSa+lu40O6m3YjWuF/rgpcxbHfZbP1r7hPSboqTxzZYOCo3p4lJEDsoOBjYqq+wg5CObCWrRG9WCHEnRTDYAQJBAO9qsDwMcgQ5oRR7Ym3r27fN0AcBZuBoFcRNE1SH5vrCjgae2G7K4xSNncYNhaFYdURd0qQCXVJpNNEehOSFZ1cCQQC3zeGyWe/VDVVGL1W1gvQ/JFfUDSfwvZwAs4iS5XHiT+G2HM9ewTLMHXsP1jC8tBQXqDaPHsbpr46NWJ0atUuBAkAIe40283HuuGP+p8h7AIpOXtpqBSCx/r4WsGxo6E/EvrPthB9C/alCByp54+zCJLIy8+gMq5DG5LdcWWp39koNAkBECJ7b51JQqAjCW877yqchoBAqW1xHTceqssmAphELVcoUIIHZbuWgi+D7MasEjhtJzmezfg7efK7lPsGYGzcBAkBttsaZOm3BSK4PTVbS4CiFzUrhLqApWFKQBv+e6LCqgJzZvlsNg+rckDlRcGVZ9TfRFYxIODUVyR3700nQqHMa
#是否加密
hasEncrypt: false

